# Generated by Django 5.2.9 on 2026-01-27 22:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('OFFER_RECEIVED', 'New offer received'), ('OFFER_ACCEPTED', 'Offer accepted'), ('OFFER_REJECTED', 'Offer rejected'), ('OFFER_EXPIRED', 'Offer expired'), ('JOB_STARTED', 'Job started'), ('JOB_COMPLETED', 'Job completed'), ('JOB_CANCELLED', 'Job cancelled'), ('ESCROW_HELD', 'Payment held in escrow'), ('ESCROW_RELEASED', 'Payment released'), ('ESCROW_REFUNDED', 'Payment refunded'), ('ESCROW_BLOCKED', 'Payment blocked'), ('DISPUTE_OPENED', 'Dispute opened'), ('DISPUTE_RESOLVED', 'Dispute resolved'), ('DISPUTE_ESCALATED', 'Dispute escalated'), ('REVIEW_RECEIVED', 'Review received'), ('TRUST_BLOCKED', 'Action blocked by trust'), ('TRUST_OVERRIDE_GRANTED', 'Trust override granted'), ('TRUST_SCORE_CHANGED', 'Trust score changed'), ('VERIFICATION_APPROVED', 'Verification approved'), ('VERIFICATION_REJECTED', 'Verification rejected'), ('SYSTEM_ALERT', 'System alert')], db_index=True, max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField(max_length=1000)),
                ('is_read', models.BooleanField(db_index=True, default=False)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional context (job_id, amount, etc.)')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_read', '-created_at'], name='notificatio_user_id_f2ad08_idx'), models.Index(fields=['user', 'type'], name='notificatio_user_id_827754_idx')],
            },
        ),
    ]
