# Generated by Django 5.2.9 on 2026-01-27 22:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_notification_system'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='category',
            field=models.CharField(choices=[('PAYMENT', 'Payment & Escrow'), ('TRUST', 'Trust & Verification'), ('JOB', 'Jobs & Offers'), ('DISPUTE', 'Disputes'), ('REVIEW', 'Reviews'), ('SYSTEM', 'System')], db_index=True, default='SYSTEM', help_text='High-level category (auto-derived from type)', max_length=20),
        ),
        migrations.AlterField(
            model_name='notification',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Additional context (job_id, amount, event, etc.)'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('OFFER_RECEIVED', 'New offer received'), ('OFFER_ACCEPTED', 'Offer accepted'), ('OFFER_REJECTED', 'Offer rejected'), ('OFFER_EXPIRED', 'Offer expired'), ('JOB_STARTED', 'Job started'), ('JOB_COMPLETED', 'Job completed'), ('JOB_CANCELLED', 'Job cancelled'), ('ESCROW_HELD', 'Payment held in escrow'), ('ESCROW_RELEASED', 'Payment released'), ('ESCROW_REFUNDED', 'Payment refunded'), ('ESCROW_BLOCKED', 'Payment blocked'), ('DISPUTE_OPENED', 'Dispute opened'), ('DISPUTE_RESOLVED', 'Dispute resolved'), ('DISPUTE_ESCALATED', 'Dispute escalated'), ('REVIEW_RECEIVED', 'Review received'), ('TRUST_BLOCKED', 'Action blocked by trust'), ('TRUST_OVERRIDE_GRANTED', 'Trust override granted'), ('TRUST_SCORE_CHANGED', 'Trust score changed'), ('VERIFICATION_APPROVED', 'Verification approved'), ('VERIFICATION_REJECTED', 'Verification rejected'), ('SYSTEM_ALERT', 'System alert')], db_index=True, help_text='Event-level type (backward compatible)', max_length=30),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'category'], name='notificatio_user_id_4652f6_idx'),
        ),
    ]
