# Generated by Django 5.2.9 on 2026-06-17 13:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_add_category_field'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('ANDROID', 'Android (FCM)'), ('IOS', 'iOS (APNS)')], help_text='Mobile platform (ANDROID or IOS)', max_length=10)),
                ('token', models.CharField(help_text='FCM registration token or APNS device token', max_length=500)),
                ('device_name', models.CharField(blank=True, help_text="Human-readable device name (e.g., 'Samsung S24')", max_length=100)),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Inactive tokens are skipped during push delivery')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_active'], name='notificatio_user_id_f0e72c_idx'), models.Index(fields=['user', 'platform', 'is_active'], name='notificatio_user_id_3ebb28_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'token'), name='unique_user_device_token')],
            },
        ),
    ]
