# Generated by Django 5.2.9 on 2026-07-17 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_devicetoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('OFFER_RECEIVED', 'New offer received'), ('OFFER_ACCEPTED', 'Offer accepted'), ('OFFER_REJECTED', 'Offer rejected'), ('OFFER_EXPIRED', 'Offer expired'), ('TRIP_REQUEST_RECEIVED', 'Trip request received'), ('TRIP_REQUEST_ACCEPTED', 'Trip request accepted'), ('TRIP_REQUEST_REJECTED', 'Trip request rejected'), ('TRIP_REQUEST_COUNTERED', 'Trip request countered'), ('MESSAGE_RECEIVED', 'New message received'), ('JOB_STARTED', 'Job started'), ('JOB_COMPLETED', 'Job completed'), ('JOB_CANCELLED', 'Job cancelled'), ('ESCROW_HELD', 'Payment held in escrow'), ('ESCROW_RELEASED', 'Payment released'), ('ESCROW_REFUNDED', 'Payment refunded'), ('ESCROW_BLOCKED', 'Payment blocked'), ('DISPUTE_OPENED', 'Dispute opened'), ('DISPUTE_RESOLVED', 'Dispute resolved'), ('DISPUTE_ESCALATED', 'Dispute escalated'), ('REVIEW_RECEIVED', 'Review received'), ('TRUST_BLOCKED', 'Action blocked by trust'), ('TRUST_OVERRIDE_GRANTED', 'Trust override granted'), ('TRUST_SCORE_CHANGED', 'Trust score changed'), ('VERIFICATION_APPROVED', 'Verification approved'), ('VERIFICATION_REJECTED', 'Verification rejected'), ('SYSTEM_ALERT', 'System alert')], db_index=True, help_text='Event-level type (backward compatible)', max_length=30),
        ),
    ]
