# Generated by Django 5.2.13 on 2026-04-19 20:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('USER_SUSPENDED', 'Utilisateur suspendu'), ('USER_ACTIVATED', 'Utilisateur réactivé'), ('PASSWORD_RESET', 'Mot de passe réinitialisé'), ('DOCUMENT_APPROVED', 'Document approuvé'), ('DOCUMENT_REJECTED', 'Document rejeté'), ('PROFILE_VERIFIED', 'Profil vérifié'), ('PROFILE_REJECTED', 'Profil rejeté'), ('DISPUTE_INVESTIGATED', 'Litige en investigation'), ('DISPUTE_RESOLVED', 'Litige résolu'), ('DISPUTE_REJECTED', 'Litige rejeté'), ('REVIEW_HIDDEN', 'Avis masqué'), ('REVIEW_SHOWN', 'Avis visible'), ('USER_WARNED', 'Utilisateur averti'), ('ESCROW_RELEASED', 'Escrow libéré'), ('COMMISSION_SETTLED', 'Commission réglée'), ('JOB_CANCELLED', 'Job annulé par admin'), ('JOB_STATUS_FORCED', 'Statut job forcé')], db_index=True, max_length=50, verbose_name='Action')),
                ('target_type', models.CharField(help_text='user, dispute, document, review, escrow, job', max_length=50, verbose_name='Type cible')),
                ('target_id', models.IntegerField(verbose_name='ID cible')),
                ('target_label', models.CharField(blank=True, default='', help_text='Human-readable label (e.g. user email, job title)', max_length=200, verbose_name='Label cible')),
                ('details', models.JSONField(blank=True, default=dict, help_text='Additional context (reason, notes, etc.)', verbose_name='Détails')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Adresse IP')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Date')),
                ('admin_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_audit_actions', to=settings.AUTH_USER_MODEL, verbose_name='Administrateur')),
            ],
            options={
                'verbose_name': 'Log admin',
                'verbose_name_plural': 'Logs admin',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['action', 'created_at'], name='admin_audit_action_9a7b7c_idx'), models.Index(fields=['admin_user', 'created_at'], name='admin_audit_admin_u_259a5f_idx')],
            },
        ),
    ]
