# Generated by Django 5.2.9 on 2025-12-26 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TrustProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verification_status', models.CharField(choices=[('UNVERIFIED', 'Unverified'), ('PENDING_REVIEW', 'Pending Review'), ('VERIFIED', 'Verified'), ('REJECTED', 'Rejected'), ('SUSPENDED', 'Suspended')], default='UNVERIFIED', max_length=20)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('last_submitted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='VerificationDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('CIN_FRONT', 'National ID (Front)'), ('CIN_BACK', 'National ID (Back)'), ('CARTE_GRISE', 'Vehicle Registration'), ('INSURANCE', 'Insurance Certificate'), ('LICENSE', 'Business License')], max_length=20)),
                ('s3_key', models.CharField(max_length=255)),
                ('encryption_iv', models.CharField(max_length=64)),
                ('file_hash', models.CharField(max_length=64)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('is_valid', models.BooleanField(default=False)),
            ],
        ),
    ]
