# Generated by Django 5.2.9 on 2025-12-26 02:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trust', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='trustprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='trust_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='verificationdocument',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='trust.trustprofile'),
        ),
        migrations.AddIndex(
            model_name='verificationdocument',
            index=models.Index(fields=['profile', 'document_type'], name='trust_verif_profile_cf7bf5_idx'),
        ),
    ]
