# Generated by Django 5.2.9 on 2026-01-16 21:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trust', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TrustVerificationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('CIN_FRONT', 'National ID (Front)'), ('CIN_BACK', 'National ID (Back)'), ('CARTE_GRISE', 'Vehicle Registration'), ('INSURANCE', 'Insurance Certificate'), ('LICENSE', 'Business License'), ('SELFIE', 'Selfie with ID')], max_length=20)),
                ('document_file', models.FileField(help_text='Upload verification document', upload_to='verification_docs/%Y/%m/')),
                ('status', models.CharField(choices=[('PENDING', 'Pending Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], db_index=True, default='PENDING', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_notes', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.AddField(
            model_name='trustprofile',
            name='trust_score',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='trustprofile',
            name='trust_score_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trustprofile',
            name='verification_status',
            field=models.CharField(choices=[('UNVERIFIED', 'Unverified'), ('PENDING', 'Pending Review'), ('VERIFIED', 'Verified'), ('REJECTED', 'Rejected'), ('SUSPENDED', 'Suspended')], db_index=True, default='UNVERIFIED', max_length=20),
        ),
        migrations.AlterField(
            model_name='verificationdocument',
            name='document_type',
            field=models.CharField(choices=[('CIN_FRONT', 'National ID (Front)'), ('CIN_BACK', 'National ID (Back)'), ('CARTE_GRISE', 'Vehicle Registration'), ('INSURANCE', 'Insurance Certificate'), ('LICENSE', 'Business License'), ('SELFIE', 'Selfie with ID')], max_length=20),
        ),
        migrations.AddIndex(
            model_name='trustprofile',
            index=models.Index(fields=['verification_status', 'trust_score'], name='trust_trust_verific_4fa72c_idx'),
        ),
        migrations.AddField(
            model_name='trustverificationrequest',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_verifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='trustverificationrequest',
            name='trust_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verification_requests', to='trust.trustprofile'),
        ),
        migrations.AddIndex(
            model_name='trustverificationrequest',
            index=models.Index(fields=['trust_profile', 'status'], name='trust_trust_trust_p_7812a1_idx'),
        ),
        migrations.AddIndex(
            model_name='trustverificationrequest',
            index=models.Index(fields=['status', 'submitted_at'], name='trust_trust_status_647af5_idx'),
        ),
        migrations.AddConstraint(
            model_name='trustverificationrequest',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'PENDING')), fields=('trust_profile',), name='unique_pending_verification_per_profile'),
        ),
    ]
