# Generated by Django 5.2.9 on 2026-01-17 16:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trust', '0003_trust_core_foundation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TrustActionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_email', models.EmailField(blank=True, help_text='Preserved email for audit even if admin deleted', max_length=254)),
                ('user_email', models.EmailField(blank=True, help_text='Preserved email for audit even if user deleted', max_length=254)),
                ('action', models.CharField(choices=[('VERIFY', 'Verify User'), ('REJECT', 'Reject User'), ('SUSPEND', 'Suspend User'), ('RESTORE', 'Restore User'), ('SCORE_UPDATE', 'Score Updated'), ('AUTO_VERIFY', 'Auto-Verified')], db_index=True, max_length=20)),
                ('previous_status', models.CharField(blank=True, choices=[('UNVERIFIED', 'Unverified'), ('PENDING', 'Pending Review'), ('VERIFIED', 'Verified'), ('REJECTED', 'Rejected'), ('SUSPENDED', 'Suspended')], max_length=20)),
                ('new_status', models.CharField(blank=True, choices=[('UNVERIFIED', 'Unverified'), ('PENDING', 'Pending Review'), ('VERIFIED', 'Verified'), ('REJECTED', 'Rejected'), ('SUSPENDED', 'Suspended')], max_length=20)),
                ('reason', models.TextField(blank=True)),
                ('metadata', models.JSONField(default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('admin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trust_admin_actions', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trust_action_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'created_at'], name='trust_trust_user_id_886038_idx'), models.Index(fields=['admin', 'created_at'], name='trust_trust_admin_i_ae0e1c_idx'), models.Index(fields=['action', 'created_at'], name='trust_trust_action_03fc33_idx')],
            },
        ),
    ]
