# Generated by Django 5.2.9 on 2026-01-18 18:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trust', '0004_trust_action_log'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TrustOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(choices=[('ESCROW', 'Allow Escrow Jobs'), ('COD', 'Allow COD Jobs'), ('ACCEPT_OFFER', 'Allow Accepting Offers'), ('ALL', 'Full Override (All Scopes)')], db_index=True, max_length=20)),
                ('granted_by_email', models.EmailField(blank=True, help_text='Preserved admin email for audit', max_length=254)),
                ('reason', models.TextField()),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('revoked', models.BooleanField(default=False)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('revoke_reason', models.TextField(blank=True)),
                ('granted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='granted_overrides', to=settings.AUTH_USER_MODEL)),
                ('revoked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revoked_overrides', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trust_overrides', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-granted_at'],
                'indexes': [models.Index(fields=['user', 'scope', 'expires_at'], name='trust_trust_user_id_753af4_idx'), models.Index(fields=['user', 'revoked', 'expires_at'], name='trust_trust_user_id_2b9b4a_idx')],
            },
        ),
    ]
