# Generated by Django 5.2.9 on 2026-01-18 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trust', '0005_trust_override'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrustPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('min_score_escrow', models.PositiveIntegerField(default=0, help_text='Minimum trust score required for escrow jobs')),
                ('min_score_cod', models.PositiveIntegerField(default=50, help_text='Minimum trust score required for COD jobs')),
                ('min_score_visibility', models.PositiveIntegerField(default=0, help_text='Minimum trust score for visibility in listings')),
                ('applies_to', models.CharField(choices=[('DEFAULT', 'Default Policy'), ('VIP', 'VIP Partners'), ('PARTNER', 'Strategic Partners')], db_index=True, default='DEFAULT', max_length=20)),
                ('is_active', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Trust Policies',
                'indexes': [models.Index(fields=['applies_to', 'is_active'], name='trust_trust_applies_d59c55_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('applies_to',), name='unique_active_policy_per_category')],
            },
        ),
    ]
