# Generated by Django 5.2.9 on 2026-02-10 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trust', '0006_trust_policy'),
    ]

    operations = [
        migrations.AddField(
            model_name='trustprofile',
            name='completion_rate',
            field=models.DecimalField(decimal_places=2, default=100.0, help_text='Percentage of accepted jobs completed successfully', max_digits=5),
        ),
        migrations.AddField(
            model_name='trustprofile',
            name='insurance_valid_until',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trustprofile',
            name='response_time_avg_minutes',
            field=models.IntegerField(blank=True, help_text='Average response time to offers in minutes', null=True),
        ),
        migrations.AddField(
            model_name='trustprofile',
            name='service_areas',
            field=models.JSONField(blank=True, default=list, help_text="List of governorates served e.g. ['Tunis', 'Sousse', 'Sfax']"),
        ),
        migrations.AddField(
            model_name='trustprofile',
            name='specializations',
            field=models.JSONField(blank=True, default=list, help_text="e.g. ['furniture', 'electronics', 'fragile', 'construction']"),
        ),
        migrations.AddField(
            model_name='trustprofile',
            name='total_jobs_completed',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='trustprofile',
            name='vehicle_capacity_kg',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Max load capacity in kg', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='trustprofile',
            name='vehicle_photos',
            field=models.JSONField(blank=True, default=list, help_text='List of vehicle photo URLs'),
        ),
        migrations.AddField(
            model_name='trustprofile',
            name='vehicle_plate',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='trustprofile',
            name='vehicle_type',
            field=models.CharField(blank=True, help_text='e.g. Pickup, Van, Truck, Camion', max_length=50),
        ),
        migrations.AlterField(
            model_name='trustpolicy',
            name='min_score_cod',
            field=models.PositiveIntegerField(default=50, help_text='Minimum trust score required for COD jobs (0-100)'),
        ),
        migrations.AlterField(
            model_name='trustpolicy',
            name='min_score_escrow',
            field=models.PositiveIntegerField(default=0, help_text='Minimum trust score required for escrow jobs (0-100)'),
        ),
        migrations.AlterField(
            model_name='trustpolicy',
            name='min_score_visibility',
            field=models.PositiveIntegerField(default=0, help_text='Minimum trust score for visibility in listings (0-100)'),
        ),
    ]
