# Generated by Django 5.2.9 on 2026-04-03 20:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trust', '0007_blueprint_alignment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='verificationdocument',
            name='rejection_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='verificationdocument',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='verificationdocument',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_documents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='trustactionlog',
            name='new_status',
            field=models.CharField(blank=True, choices=[('UNVERIFIED', 'Unverified'), ('PENDING', 'Pending Review'), ('PARTIALLY_REVIEWED', 'Partially Reviewed'), ('VERIFIED', 'Verified'), ('REJECTED', 'Rejected'), ('SUSPENDED', 'Suspended')], max_length=20),
        ),
        migrations.AlterField(
            model_name='trustactionlog',
            name='previous_status',
            field=models.CharField(blank=True, choices=[('UNVERIFIED', 'Unverified'), ('PENDING', 'Pending Review'), ('PARTIALLY_REVIEWED', 'Partially Reviewed'), ('VERIFIED', 'Verified'), ('REJECTED', 'Rejected'), ('SUSPENDED', 'Suspended')], max_length=20),
        ),
        migrations.AlterField(
            model_name='trustprofile',
            name='verification_status',
            field=models.CharField(choices=[('UNVERIFIED', 'Unverified'), ('PENDING', 'Pending Review'), ('PARTIALLY_REVIEWED', 'Partially Reviewed'), ('VERIFIED', 'Verified'), ('REJECTED', 'Rejected'), ('SUSPENDED', 'Suspended')], db_index=True, default='UNVERIFIED', max_length=20),
        ),
    ]
