# Generated by Django 5.2.16 on 2026-07-13 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trust', '0008_document_review_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trustverificationrequest',
            name='document_type',
            field=models.CharField(choices=[('CIN_FRONT', 'National ID (Front)'), ('CIN_BACK', 'National ID (Back)'), ('LICENSE_FRONT', 'Driving License (Front)'), ('LICENSE_BACK', 'Driving License (Back)'), ('CARTE_GRISE_FRONT', 'Vehicle Registration (Front)'), ('CARTE_GRISE_BACK', 'Vehicle Registration (Back)'), ('INSURANCE_FRONT', 'Insurance Certificate (Front)'), ('INSURANCE_BACK', 'Insurance Certificate (Back)'), ('SELFIE', 'Selfie with ID'), ('CARTE_GRISE', 'Vehicle Registration (Legacy)'), ('INSURANCE', 'Insurance Certificate (Legacy)'), ('LICENSE', 'Business License (Legacy)')], max_length=20),
        ),
        migrations.AlterField(
            model_name='verificationdocument',
            name='document_type',
            field=models.CharField(choices=[('CIN_FRONT', 'National ID (Front)'), ('CIN_BACK', 'National ID (Back)'), ('LICENSE_FRONT', 'Driving License (Front)'), ('LICENSE_BACK', 'Driving License (Back)'), ('CARTE_GRISE_FRONT', 'Vehicle Registration (Front)'), ('CARTE_GRISE_BACK', 'Vehicle Registration (Back)'), ('INSURANCE_FRONT', 'Insurance Certificate (Front)'), ('INSURANCE_BACK', 'Insurance Certificate (Back)'), ('SELFIE', 'Selfie with ID'), ('CARTE_GRISE', 'Vehicle Registration (Legacy)'), ('INSURANCE', 'Insurance Certificate (Legacy)'), ('LICENSE', 'Business License (Legacy)')], max_length=20),
        ),
    ]
