# Generated by Django 5.2.9 on 2026-07-20 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trust', '0009_alter_trustverificationrequest_document_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='verificationdocument',
            name='expires_at',
            field=models.DateField(blank=True, null=True),
        ),
    ]
