# Generated by Django 5.2.9 on 2026-01-01 23:39

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyEngagementScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('login_score', models.PositiveIntegerField(default=0)),
                ('job_view_score', models.PositiveIntegerField(default=0)),
                ('job_create_score', models.PositiveIntegerField(default=0)),
                ('offer_submit_score', models.PositiveIntegerField(default=0)),
                ('offer_accepted_score', models.PositiveIntegerField(default=0)),
                ('payment_completed_score', models.PositiveIntegerField(default=0)),
                ('total_score', models.PositiveIntegerField(db_index=True, default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='engagement_scores', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['user', 'date'], name='analytics_d_user_id_bba5d8_idx'), models.Index(fields=['date', 'total_score'], name='analytics_d_date_862ba6_idx')],
                'unique_together': {('user', 'date')},
            },
        ),
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ('started_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('last_activity_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['user', 'started_at'], name='analytics_u_user_id_c1ab02_idx'), models.Index(fields=['user', 'ended_at'], name='analytics_u_user_id_0c42ad_idx')],
            },
        ),
    ]
