# Generated by Django 5.2.9 on 2026-01-02 23:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyUserSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('engagement_score', models.PositiveIntegerField(default=0)),
                ('trust_score', models.PositiveIntegerField(default=0)),
                ('segments', models.JSONField(default=dict)),
                ('revenue_generated', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_snapshots', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['user', 'date'], name='analytics_d_user_id_051afc_idx'), models.Index(fields=['date', 'trust_score'], name='analytics_d_date_62bc70_idx'), models.Index(fields=['date', 'revenue_generated'], name='analytics_d_date_874ce7_idx')],
                'unique_together': {('user', 'date')},
            },
        ),
    ]
