# Generated by Django 5.2.9 on 2026-01-17 01:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_dailyusersnapshot'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SecurityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('ADMIN_LOGIN_SUCCESS', 'Admin Login Success'), ('ADMIN_LOGIN_FAILED', 'Admin Login Failed'), ('ADMIN_ACCOUNT_LOCKED', 'Admin Account Locked'), ('ADMIN_SESSION_REVOKED', 'Admin Session Revoked'), ('ADMIN_SESSION_CREATED', 'Admin Session Created'), ('ADMIN_PASSWORD_CHANGED', 'Admin Password Changed'), ('ADMIN_LOGOUT', 'Admin Logout'), ('SECURITY_EVENT', 'Security Event')], db_index=True, max_length=50)),
                ('actor_email', models.EmailField(blank=True, help_text='Email at time of event (preserved even if user deleted)', max_length=254)),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField(blank=True, max_length=500)),
                ('metadata', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='security_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'managed': True,
                'indexes': [models.Index(fields=['event_type', 'created_at'], name='analytics_s_event_t_93ded8_idx'), models.Index(fields=['actor', 'created_at'], name='analytics_s_actor_i_9c8093_idx'), models.Index(fields=['ip_address', 'created_at'], name='analytics_s_ip_addr_cfd9da_idx')],
            },
        ),
    ]
