# Generated by Django 5.2.9 on 2026-01-25 22:58

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('logistics', '0003_alter_offer_commission_amount_alter_offer_price_net_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('CLIENT', 'Client reviewing Transporter'), ('TRANSPORTER', 'Transporter reviewing Client')], db_index=True, max_length=20)),
                ('rating', models.PositiveSmallIntegerField(help_text='Rating from 1 (poor) to 5 (excellent)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comment', models.TextField(blank=True, help_text='Optional review comment', max_length=1000)),
                ('is_flagged', models.BooleanField(default=False, help_text='Review flagged for potential abuse')),
                ('flag_reason', models.CharField(blank=True, max_length=200)),
                ('trust_impact_applied', models.BooleanField(default=False, help_text='Whether this review has been applied to trust score')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reviews', to='logistics.transportjob')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reviews_given', to=settings.AUTH_USER_MODEL)),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reviews_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReviewAbuseLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detector', models.CharField(help_text='Name of abuse detector that triggered', max_length=50)),
                ('reason', models.TextField()),
                ('reviewer_id', models.IntegerField()),
                ('target_id', models.IntegerField()),
                ('severity', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='MEDIUM', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('review', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='abuse_logs', to='reviews.review')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['target', 'created_at'], name='reviews_rev_target__c10554_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['reviewer', 'created_at'], name='reviews_rev_reviewe_06e3c4_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['is_flagged'], name='reviews_rev_is_flag_790b01_idx'),
        ),
        migrations.AddConstraint(
            model_name='review',
            constraint=models.UniqueConstraint(fields=('job', 'role'), name='one_review_per_job_per_role'),
        ),
        migrations.AddConstraint(
            model_name='review',
            constraint=models.CheckConstraint(condition=models.Q(('rating__gte', 1), ('rating__lte', 5)), name='rating_1_to_5'),
        ),
    ]
