# Generated by Django 5.2.9 on 2026-02-10 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_review_system'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='aspects',
            field=models.JSONField(blank=True, default=dict, help_text="Aspect ratings e.g. {'punctuality': 5, 'care': 4, 'professionalism': 5}"),
        ),
    ]
