# Generated by Django 5.2.9 on 2025-12-26 02:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('logistics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EscrowTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('INITIATED', 'Initiated'), ('HELD', 'Held (Escrow)'), ('RELEASED', 'Released to Transporter'), ('REFUNDED', 'Refunded to Client'), ('FAILED', 'Failed')], default='INITIATED', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('gateway_reference', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CommissionLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_settled', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('settled_at', models.DateTimeField(blank=True, null=True)),
                ('job_reference', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='commission_entry', to='logistics.transportjob')),
            ],
        ),
    ]
