# Generated by Django 5.2.9 on 2025-12-26 02:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('logistics', '0002_initial'),
        ('payments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='commissionledger',
            name='transporter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='commission_ledger', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='escrowtransaction',
            name='booking_reference',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='escrow_transactions', to='logistics.transportjob'),
        ),
    ]
