# Generated by Django 5.2.9 on 2025-12-27 00:02

import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0003_alter_offer_commission_amount_alter_offer_price_net_and_more'),
        ('payments', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='commissionledger',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='commissionledger',
            name='is_settled',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='escrowtransaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='escrowtransaction',
            name='status',
            field=models.CharField(choices=[('INITIATED', 'Initiated'), ('HELD', 'Held (Escrow)'), ('RELEASED', 'Released to Transporter'), ('REFUNDED', 'Refunded to Client'), ('FAILED', 'Failed')], db_index=True, default='INITIATED', max_length=20),
        ),
        migrations.AddIndex(
            model_name='commissionledger',
            index=models.Index(fields=['transporter', 'is_settled'], name='payments_co_transpo_376ff6_idx'),
        ),
        migrations.AddIndex(
            model_name='escrowtransaction',
            index=models.Index(fields=['booking_reference', 'status'], name='payments_es_booking_aad0c8_idx'),
        ),
        migrations.AddConstraint(
            model_name='commissionledger',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gte', 0)), name='commission_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='escrowtransaction',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gte', 0)), name='escrow_amount_positive'),
        ),
    ]
