# Generated by Django 5.2.9 on 2026-02-10 00:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0004_blueprint_alignment'),
        ('payments', '0003_alter_commissionledger_amount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('final_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('commission_rate', models.DecimalField(decimal_places=4, help_text='Commission rate applied (e.g., 0.1500 for 15%)', max_digits=5)),
                ('payment_method', models.CharField(choices=[('DIGITAL', 'Digital Payment (Escrow)'), ('COD', 'Cash on Delivery')], default='DIGITAL', max_length=20)),
                ('cod_allowed', models.BooleanField(default=True, help_text='Whether COD was allowed for this booking amount')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('accepted_offer', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='booking', to='logistics.offer')),
                ('job', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='booking', to='logistics.transportjob')),
            ],
            options={
                'indexes': [models.Index(fields=['payment_method', 'created_at'], name='payments_bo_payment_68e8a8_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('final_price__gte', 0)), name='booking_price_positive')],
            },
        ),
    ]
