# Generated by Django 5.2.9 on 2026-07-18 22:06

import payments.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_withdrawalrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='delivery_pin',
            field=models.CharField(default=payments.models.generate_delivery_pin, help_text='4-digit code the client gives at delivery (POD)', max_length=4),
        ),
    ]
