# Generated by Django 5.2.16 on 2026-07-21 20:04

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0013_jobevent'),
        ('payments', '0006_booking_delivery_pin'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RefundRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beneficiary_type', models.CharField(choices=[('CLIENT', 'Client (refund)'), ('TRANSPORTER', 'Transporter (split share)')], db_index=True, default='CLIENT', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('gateway_reference', models.CharField(blank=True, max_length=100)),
                ('auto_executed', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('REQUESTED', 'Requested'), ('PROCESSING', 'Processing'), ('PAID', 'Paid'), ('REJECTED', 'Rejected')], db_index=True, default='REQUESTED', max_length=20)),
                ('reason', models.CharField(blank=True, default='', max_length=255)),
                ('admin_note', models.CharField(blank=True, default='', max_length=255)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('beneficiary', models.ForeignKey(help_text='User who must receive the money', on_delete=django.db.models.deletion.PROTECT, related_name='refund_requests', to=settings.AUTH_USER_MODEL)),
                ('escrow', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='refund_requests', to='payments.escrowtransaction')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='refund_requests', to='logistics.transportjob')),
            ],
            options={
                'ordering': ['-requested_at'],
                'indexes': [models.Index(fields=['beneficiary', 'status'], name='payments_re_benefic_7f879a_idx'), models.Index(fields=['status', 'requested_at'], name='payments_re_status_524eab_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='refund_amount_positive')],
            },
        ),
    ]
