# Generated by Django 5.2.9 on 2025-12-26 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected'), ('EXPIRED', 'Expired'), ('WITHDRAWN', 'Withdrawn')], default='PENDING', max_length=20)),
                ('price_net', models.DecimalField(decimal_places=2, help_text='Amount Transporter receives', max_digits=10)),
                ('commission_amount', models.DecimalField(decimal_places=2, help_text='Platform fee', max_digits=10)),
                ('total_price', models.DecimalField(decimal_places=2, help_text='Price Client pays', max_digits=10)),
                ('message', models.TextField(blank=True)),
                ('valid_until', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TransportJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Published'), ('MATCHED', 'Matched'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('DISPUTED', 'Disputed')], default='DRAFT', max_length=20)),
                ('job_type', models.CharField(choices=[('TRANSPORT', 'Transport'), ('MOVING', 'Moving (Déménagement)')], max_length=20)),
                ('pickup_address', models.CharField(max_length=255)),
                ('pickup_lat', models.DecimalField(decimal_places=6, max_digits=9, null=True)),
                ('pickup_lng', models.DecimalField(decimal_places=6, max_digits=9, null=True)),
                ('dropoff_address', models.CharField(max_length=255)),
                ('dropoff_lat', models.DecimalField(decimal_places=6, max_digits=9, null=True)),
                ('dropoff_lng', models.DecimalField(decimal_places=6, max_digits=9, null=True)),
                ('scheduled_time', models.DateTimeField()),
                ('specifications', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
