# Generated by Django 5.2.9 on 2025-12-26 02:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('logistics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='transporter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='offers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='transportjob',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='jobs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='offer',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='logistics.transportjob'),
        ),
    ]
