# Generated by Django 5.2.9 on 2025-12-27 00:02

import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='commission_amount',
            field=models.DecimalField(decimal_places=2, help_text='Platform fee', max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='offer',
            name='price_net',
            field=models.DecimalField(decimal_places=2, help_text='Amount Transporter receives', max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='offer',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected'), ('EXPIRED', 'Expired'), ('WITHDRAWN', 'Withdrawn')], db_index=True, default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='offer',
            name='total_price',
            field=models.DecimalField(decimal_places=2, help_text='Price Client pays', max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='transportjob',
            name='scheduled_time',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='transportjob',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Published'), ('MATCHED', 'Matched'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('DISPUTED', 'Disputed')], db_index=True, default='DRAFT', max_length=20),
        ),
        migrations.AddIndex(
            model_name='offer',
            index=models.Index(fields=['transporter', 'status'], name='logistics_o_transpo_44445e_idx'),
        ),
        migrations.AddIndex(
            model_name='offer',
            index=models.Index(fields=['job', 'status'], name='logistics_o_job_id_4ea5cd_idx'),
        ),
        migrations.AddIndex(
            model_name='transportjob',
            index=models.Index(fields=['owner', 'status'], name='logistics_t_owner_i_4ccff2_idx'),
        ),
        migrations.AddIndex(
            model_name='transportjob',
            index=models.Index(fields=['status', 'scheduled_time'], name='logistics_t_status_9cc1dc_idx'),
        ),
        migrations.AddConstraint(
            model_name='offer',
            constraint=models.CheckConstraint(condition=models.Q(('total_price__gte', models.F('price_net'))), name='offer_total_gte_net'),
        ),
        migrations.AddConstraint(
            model_name='offer',
            constraint=models.CheckConstraint(condition=models.Q(('price_net__gte', 0)), name='offer_price_net_positive'),
        ),
        migrations.AddConstraint(
            model_name='offer',
            constraint=models.CheckConstraint(condition=models.Q(('commission_amount__gte', 0)), name='offer_commission_positive'),
        ),
    ]
