# Generated by Django 5.2.9 on 2026-02-10 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0003_alter_offer_commission_amount_alter_offer_price_net_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transportjob',
            name='description',
            field=models.TextField(blank=True, help_text='What needs transporting'),
        ),
        migrations.AddField(
            model_name='transportjob',
            name='dropoff_governorate',
            field=models.CharField(blank=True, db_index=True, max_length=50),
        ),
        migrations.AddField(
            model_name='transportjob',
            name='photos',
            field=models.JSONField(blank=True, default=list, help_text='List of photo URLs for job items'),
        ),
        migrations.AddField(
            model_name='transportjob',
            name='pickup_governorate',
            field=models.CharField(blank=True, db_index=True, max_length=50),
        ),
        migrations.AddField(
            model_name='transportjob',
            name='price_tnd_max',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Client's maximum budget hint (TND)", max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='transportjob',
            name='price_tnd_min',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Client's minimum budget hint (TND)", max_digits=10, null=True),
        ),
    ]
