# Generated by Django 5.2.9 on 2026-03-21 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0004_blueprint_alignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='transportjob',
            name='dropoff_hint',
            field=models.TextField(blank=True, help_text='Location tip for dropoff (floor, door code, landmark...)'),
        ),
        migrations.AddField(
            model_name='transportjob',
            name='pickup_hint',
            field=models.TextField(blank=True, help_text='Location tip for pickup (floor, door code, landmark...)'),
        ),
    ]
