# Generated by Django 5.2.13 on 2026-04-14 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0005_transportjob_dropoff_hint_transportjob_pickup_hint'),
    ]

    operations = [
        migrations.AddField(
            model_name='transportjob',
            name='available_capacity',
            field=models.CharField(blank=True, help_text="Available capacity description for return trips (e.g. '2 tonnes, camion bâché')", max_length=255),
        ),
        migrations.AddField(
            model_name='transportjob',
            name='is_return_trip',
            field=models.BooleanField(db_index=True, default=False, help_text='True if created by a transporter indicating return trip availability'),
        ),
    ]
