# Generated by Django 5.2.12 on 2026-04-30 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0008_seed_pricing_grids'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricinggrid',
            name='job_type',
            field=models.CharField(choices=[('TRANSPORT', 'Transport'), ('MOVING', 'Moving (Déménagement)'), ('DELIVERY', 'Delivery (Livraison)')], db_index=True, help_text='Type de job (TRANSPORT ou MOVING)', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='transportjob',
            name='job_type',
            field=models.CharField(choices=[('TRANSPORT', 'Transport'), ('MOVING', 'Moving (Déménagement)'), ('DELIVERY', 'Delivery (Livraison)')], max_length=20),
        ),
    ]
