# Generated by Django 5.2.9 on 2026-07-17 17:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0010_add_viewcount_favorites_counteroffers'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='transportjob',
            name='distance_km',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Estimated road distance in km (haversine × 1.25), set at creation', max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='transportjob',
            name='instant_booking',
            field=models.BooleanField(default=False, help_text='D11: return trips only — allow direct booking without a structured request (off by default)'),
        ),
        migrations.CreateModel(
            name='ReturnTripRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(help_text='What the client wants to ship (goods, weight estimate...)', max_length=1000)),
                ('photos', models.JSONField(blank=True, default=list, help_text='List of photo URLs (PhotoUploadView)')),
                ('proposed_price', models.DecimalField(decimal_places=2, help_text='Client-facing total price proposed by the client (TND)', max_digits=10)),
                ('payment_method', models.CharField(choices=[('DIGITAL', 'Digital Payment (Escrow)'), ('COD', 'Cash on Delivery')], default='DIGITAL', max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected'), ('COUNTERED', 'Countered'), ('CANCELLED', 'Cancelled'), ('EXPIRED', 'Expired')], db_index=True, default='PENDING', max_length=20)),
                ('counter_price', models.DecimalField(blank=True, decimal_places=2, help_text="Transporter's counter-proposal (client-facing total, TND)", max_digits=10, null=True)),
                ('response_message', models.CharField(blank=True, default='', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trip_requests', to=settings.AUTH_USER_MODEL)),
                ('job', models.ForeignKey(limit_choices_to={'is_return_trip': True}, on_delete=django.db.models.deletion.CASCADE, related_name='trip_requests', to='logistics.transportjob')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['job', 'status'], name='logistics_r_job_id_1b1263_idx'), models.Index(fields=['client', 'status'], name='logistics_r_client__9bdb05_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('proposed_price__gt', 0)), name='trip_request_price_positive')],
            },
        ),
    ]
