# Generated by Django 5.2.9 on 2026-07-18 22:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0012_corridoralert'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(choices=[('ARRIVED_PICKUP', 'Arrived at pickup'), ('LOADED', 'Loaded / en route'), ('DELIVERED', 'Delivered (with proof)'), ('CANCELLED_BY_TRANSPORTER', 'Cancelled by transporter'), ('CANCELLED_BY_CLIENT', 'Cancelled by client')], db_index=True, max_length=30)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Context (pod_photo_url, reason, ...)')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_events', to=settings.AUTH_USER_MODEL)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='logistics.transportjob')),
            ],
            options={
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['job', 'event'], name='logistics_j_job_id_afaa20_idx')],
            },
        ),
    ]
