# Generated by Django 5.2.9 on 2026-08-04 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0013_jobevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='transportjob',
            name='route_polyline',
            field=models.TextField(blank=True, default='', help_text='Encoded polyline (precision 5) of the driving route, empty when routing failed'),
        ),
        migrations.AlterField(
            model_name='transportjob',
            name='distance_km',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Road distance in km, from the router or haversine × 1.25 fallback, set at creation', max_digits=7, null=True),
        ),
    ]
