"""
Analytics Models - Transporti V1
Session tracking, engagement scoring, and data valorization snapshots.
"""
import uuid
from django.db import models
from django.conf import settings
from django.utils import timezone


class UserSession(models.Model):
    """
    Tracks user sessions for time-spent analytics.
    A session is closed after 30 minutes of inactivity.
    """
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        related_name='sessions'
    )
    session_id = models.UUIDField(default=uuid.uuid4, unique=True, db_index=True)
    
    started_at = models.DateTimeField(auto_now_add=True, db_index=True)
    last_activity_at = models.DateTimeField(auto_now_add=True)
    ended_at = models.DateTimeField(null=True, blank=True)
    
    # Computed on session close
    duration_seconds = models.PositiveIntegerField(null=True, blank=True)
    
    class Meta:
        indexes = [
            models.Index(fields=['user', 'started_at']),
            models.Index(fields=['user', 'ended_at']),
        ]
        ordering = ['-started_at']
    
    def __str__(self):
        return f"Session {self.session_id} - {self.user.email}"
    
    @property
    def is_active(self) -> bool:
        """Session is active if no end time and activity within 30 min."""
        if self.ended_at:
            return False
        return timezone.now() - self.last_activity_at <= timezone.timedelta(minutes=30)
    
    def close_session(self):
        """Close session and compute duration."""
        if not self.ended_at:
            self.ended_at = self.last_activity_at
            self.duration_seconds = int(
                (self.last_activity_at - self.started_at).total_seconds()
            )
            self.save()


class DailyEngagementScore(models.Model):
    """
    Daily engagement score per user.
    Computed from user actions (login, job creation, offers, etc.)
    """
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        related_name='engagement_scores'
    )
    date = models.DateField(db_index=True)
    
    # Score breakdown (allows analysis)
    login_score = models.PositiveIntegerField(default=0)
    job_view_score = models.PositiveIntegerField(default=0)
    job_create_score = models.PositiveIntegerField(default=0)
    offer_submit_score = models.PositiveIntegerField(default=0)
    offer_accepted_score = models.PositiveIntegerField(default=0)
    payment_completed_score = models.PositiveIntegerField(default=0)
    
    # Total computed score
    total_score = models.PositiveIntegerField(default=0, db_index=True)
    
    class Meta:
        unique_together = ['user', 'date']
        indexes = [
            models.Index(fields=['user', 'date']),
            models.Index(fields=['date', 'total_score']),
        ]
        ordering = ['-date']
    
    def __str__(self):
        return f"{self.user.email} - {self.date}: {self.total_score} pts"
    
    def recalculate_total(self):
        """Sum all score components."""
        self.total_score = (
            self.login_score +
            self.job_view_score +
            self.job_create_score +
            self.offer_submit_score +
            self.offer_accepted_score +
            self.payment_completed_score
        )
        self.save()


class DailyUserSnapshot(models.Model):
    """
    Daily snapshot of user metrics for historical tracking and investor analytics.
    Generated by daily cron job. Idempotent (one per user per day).
    """
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        related_name='daily_snapshots'
    )
    date = models.DateField(db_index=True)
    
    # Engagement
    engagement_score = models.PositiveIntegerField(default=0)
    
    # Trust (0-100)
    trust_score = models.PositiveIntegerField(default=0)
    
    # Segments (JSON: is_power_user, is_at_risk_churn, etc.)
    segments = models.JSONField(default=dict)
    
    # Economic (revenue generated by this user for platform)
    revenue_generated = models.DecimalField(
        max_digits=12, decimal_places=3, default=0
    )
    
    # Metadata
    created_at = models.DateTimeField(auto_now_add=True)
    
    class Meta:
        unique_together = ['user', 'date']
        indexes = [
            models.Index(fields=['user', 'date']),
            models.Index(fields=['date', 'trust_score']),
            models.Index(fields=['date', 'revenue_generated']),
        ]
        ordering = ['-date']
    
    def __str__(self):
        return f"Snapshot {self.user.email} - {self.date}"


class SecurityLog(models.Model):
    """
    Immutable security event log for admin operations.
    NO UPDATE OR DELETE ALLOWED.
    
    Used for:
    - Admin login success/failure
    - Session revocation
    - Account lockout
    - Password changes
    """
    class EventType(models.TextChoices):
        ADMIN_LOGIN_SUCCESS = 'ADMIN_LOGIN_SUCCESS', 'Admin Login Success'
        ADMIN_LOGIN_FAILED = 'ADMIN_LOGIN_FAILED', 'Admin Login Failed'
        ADMIN_ACCOUNT_LOCKED = 'ADMIN_ACCOUNT_LOCKED', 'Admin Account Locked'
        ADMIN_SESSION_REVOKED = 'ADMIN_SESSION_REVOKED', 'Admin Session Revoked'
        ADMIN_SESSION_CREATED = 'ADMIN_SESSION_CREATED', 'Admin Session Created'
        ADMIN_PASSWORD_CHANGED = 'ADMIN_PASSWORD_CHANGED', 'Admin Password Changed'
        ADMIN_LOGOUT = 'ADMIN_LOGOUT', 'Admin Logout'
        SECURITY_EVENT = 'SECURITY_EVENT', 'Security Event'
    
    event_type = models.CharField(
        max_length=50,
        choices=EventType.choices,
        db_index=True
    )
    
    # Actor (may be null for failed login attempts)
    actor = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name='security_logs'
    )
    actor_email = models.EmailField(
        blank=True,
        help_text="Email at time of event (preserved even if user deleted)"
    )
    
    # Request context
    ip_address = models.GenericIPAddressField()
    user_agent = models.TextField(blank=True, max_length=500)
    
    # Flexible metadata
    metadata = models.JSONField(default=dict)
    
    # Immutable timestamp
    created_at = models.DateTimeField(auto_now_add=True, db_index=True)
    
    class Meta:
        indexes = [
            models.Index(fields=['event_type', 'created_at']),
            models.Index(fields=['actor', 'created_at']),
            models.Index(fields=['ip_address', 'created_at']),
        ]
        ordering = ['-created_at']
        # Prevent bulk updates/deletes at Django level
        managed = True
    
    def __str__(self):
        return f"{self.event_type} - {self.actor_email or 'anonymous'} @ {self.created_at}"
    
    def save(self, *args, **kwargs):
        """Prevent updates to existing records."""
        if self.pk:
            raise ValueError("SecurityLog entries cannot be modified.")
        super().save(*args, **kwargs)
    
    def delete(self, *args, **kwargs):
        """Prevent deletion."""
        raise ValueError("SecurityLog entries cannot be deleted.")
