# Generated by Django 5.2.9 on 2025-12-27 00:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0003_alter_offer_commission_amount_alter_offer_price_net_and_more'),
        ('support', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auditlog',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='actor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_actions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='target_entity',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='dispute',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Open'), ('INVESTIGATING', 'Investigating'), ('RESOLVED', 'Resolved'), ('DISMISSED', 'Dismissed')], db_index=True, default='OPEN', max_length=20),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['actor', 'timestamp'], name='support_aud_actor_i_4e5083_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['action', 'timestamp'], name='support_aud_action_970827_idx'),
        ),
        migrations.AddIndex(
            model_name='dispute',
            index=models.Index(fields=['status', 'created_at'], name='support_dis_status_6098b3_idx'),
        ),
        migrations.AddIndex(
            model_name='dispute',
            index=models.Index(fields=['job', 'status'], name='support_dis_job_id_08f029_idx'),
        ),
    ]
