# Generated by Django 5.2.9 on 2026-01-09 23:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0003_alter_offer_commission_amount_alter_offer_price_net_and_more'),
        ('support', '0003_alter_auditlog_options_alter_auditlog_action_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='dispute',
            old_name='initiator',
            new_name='opened_by',
        ),
        migrations.AddField(
            model_name='dispute',
            name='resolved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_disputes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dispute',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='dispute',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='dispute',
            name='reason',
            field=models.CharField(choices=[('DAMAGED_ITEMS', 'Damaged Items'), ('NO_SHOW', 'No Show'), ('PAYMENT_ISSUE', 'Payment Issue'), ('LATE_DELIVERY', 'Late Delivery'), ('HARASSMENT', 'Harassment'), ('FRAUD', 'Suspected Fraud'), ('OTHER', 'Other')], max_length=50),
        ),
        migrations.AlterField(
            model_name='dispute',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Open'), ('INVESTIGATING', 'Investigating'), ('RESOLVED', 'Resolved'), ('REJECTED', 'Rejected')], db_index=True, default='OPEN', max_length=20),
        ),
        migrations.AddIndex(
            model_name='dispute',
            index=models.Index(fields=['opened_by', 'created_at'], name='support_dis_opened__1e4079_idx'),
        ),
        migrations.AddConstraint(
            model_name='dispute',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['OPEN', 'INVESTIGATING'])), fields=('job',), name='unique_active_dispute_per_job'),
        ),
    ]
