# Generated by Django 5.2.16 on 2026-07-21 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0004_dispute_lifecycle_hardening'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispute',
            name='resolution_outcome',
            field=models.CharField(choices=[('NONE', 'Notes only (no escrow movement)'), ('REFUND_CLIENT', 'Refund client (full)'), ('RELEASE_TRANSPORTER', 'Release to transporter'), ('SPLIT', 'Split (partial refund)')], db_index=True, default='NONE', help_text='Financial outcome that drove the escrow movement at resolution', max_length=20),
        ),
    ]
